name: mini_catalog_app
description: Mini Katalog Uygulaması - Ürünleri listelemek ve görmek için bir Flutter uygulaması

# Proje versiyonu
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Görselleri (Assets) yapılandırması
  assets:
    - assets/banners/
    - assets/images/
    - assets/icons/

  # Yazı tipi yapılandırması (isteğe bağlı)
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Bold.ttf
  #         weight: 700
